계획 수정 시 기존 사진 불러오는 기능 추가
boostcampwm-2021/android03-Contact pull request #306
Opened 2022-01-21 15:05 UTC by WonJoongLee

## Issue
- close #305 

## Overview
- 계획 수정 시 기존 사진 불러와서 현재 사진 list에 반영
- 기존 사진에 추가 기능
- 기존 사진 삭제 기능
- Glide에 캐시가 적용되어 이전 사진이 보이는 것 캐시 비활성화

## Screenshot

https://user-images.githubusercontent.com/57510192/150549501-f9ccc31d-f29f-4771-8372-2ee40c74652f.mp4

2022-01-22 19:01 UTC, tyehooney requested changes
확인했습니다~

2022-01-22 19:01 UTC, tyehooney commented on data/src/main/java/com/ivyclub/data/image/ImageManager.kt
>              bitmapList.forEachIndexed { index, bitmap ->
`file.mkdirs()` 부분을 if 블록 밖으로 빼면 한번만 쓸 수 있을 것 같아요!

2022-01-23 00:04 UTC, WonJoongLee commented on data/src/main/java/com/ivyclub/data/image/ImageManager.kt
>              bitmapList.forEachIndexed { index, bitmap ->
아 그렇네요ㅎㅎ 수정하겠습니다.

2022-01-23 09:12 UTC, tyehooney approved these changes

2022-01-24 01:03 UTC, merged